name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          project_id: ${{ secrets.GAE_PROJECT_ID }}
          credentials: ${{ secrets.GAE_PRIVATE_KEY }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
