name: Go

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set up config.env
        env: 
          CONFIG_ENV: ${{format('token={0}\nchatId={1}', secrets.TG_TOKEN, secrets.TG_CHAT_ID)}}
        run: echo "$CONFIG_ENV" >> config.env
      - name: ls 
        run: pwd && ls -alt ./
      - name: cat
        run: cat ./config.env
    
