name: Go

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set up config.env
        env: 
          CONFIG_ENV: ${{format('token={0}\nchatId={1}', secrets.TG_TOKEN, secrets.TG_CHAT_ID)}}
        run: echo "$CONFIG_ENV" >> config.env
      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          project_id: ${{ secrets.GAE_PROJECT_ID }}
          credentials: ${{ secrets.GAE_PRIVATE_KEY }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
