name: Go

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set up config.env
        env: 
          TOKEN: ${{format('token={0}', secrets.TG_TOKEN)}}
          CHAT_ID: ${{format('chatId={0}', secrets.TG_CHAT_ID)}} 
        run: |
          echo "$TOKEN" >> config.env
          echo "$CHAT_ID" >> config.env
      - name: cat config.env
        run: cat ./config.env
      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml cron.yaml
          project_id: ${{ secrets.GAE_PROJECT_ID }}
          credentials: ${{ secrets.GAE_PRIVATE_KEY }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
